name: codspeed-benchmarks

on:
  push:
    branches:
      - "main" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

env:
  TURBOPACK_BENCH_COUNTS: 50

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed
          cache-base: main

      - name: Build the benchmark target(s)
        run: |
          cargo codspeed build -p turbo-tasks-fs
          cargo codspeed build -p turbo-tasks-memory
          cargo codspeed build -p turbopack
          # cargo codspeed build -p turbopack-bench    # disabled for now because it uses a custom benchmark iterator
          cargo codspeed build -p turbopack-cli
          cargo codspeed build -p turbopack-ecmascript

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: cargo codspeed run
